import "pkg:/source/roku_modules/maestro/core/MIOC.brs"
import "pkg:/source/roku_modules/maestro/core/Tasks.brs"
import "pkg:/source/roku_modules/maestro/core/Utils.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function Init()
  mv.initializeFocusManager(m.global)
  tick = m.top.getScene().createChild("Timer")
  tick.duration = 0.01
  tick.repeat = true
  tick.control = "start"
  mc.setOrAddNodeField(m.global, "tick", tick)
  mc.tasks.observeNodeField(tick, "fire", onInfoChange, "none")
  initFlyweight()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ flyweight
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function initFlyweight()
  m.cellProvider = createObject("roSGNode", "CellProvider")
  m.global.addFields({ "cellProvider": m.cellProvider })

  m.cellTracker = createObject("roSGNode", "CellTracker")
  m.global.addFields({ "cellTracker": m.cellTracker })
  m.top.addFields({ "_global": m.global })

  m.infoLabel = m.top.findNode("infoLabel")

end function

function prebakeCells()
  m.cellProvider@.addPreBakedCells(200, "ml_SimpleCell")
end function


'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ callbacks
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function onInfoChange()
  m.infoLabel.text = " Light cells (" + str(m.cellTracker.numberOfCellsInUse) + "/" + str(m.cellTracker.numberOfCells) + ") - Real cells (" + str(m.cellProvider.numberOfCellsInUse) + "/" + str(m.cellProvider.numberOfCells) + ")"
end function


'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ lifecycle
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function onFirstShow()
  m.log.info("onFirstShow")
  prebakeCells()
  screen = mc.createSGNode("ListScreen", m.top.findNode("contentGroup"), "listScreen")
  mv.setFocus(screen)
end function
