import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/roku_modules/maestro/core/MIOC.brs"
import "pkg:/source/roku_modules/maestro/core/Tasks.brs"
import "pkg:/source/roku_modules/maestro/core/Utils.brs"
import "pkg:/components/roku_modules/maestro/view/mixin/FocusMixin.brs"

function Init() as void
  createObject("roSGNode", "TrackerTask")

  m.global.addFields({ "isFocusLocked": false })
  m.top._rLog = log.initializeLogManager(["log_PrintTransport"], 2)
  ' m.top._rLog = log.initializeLogManager(["log_PrintTransport", "log_ScreenTransport"], 5)
  m.log = new log.Logger("MainScene")
  m.log.info("Maestro List 1.0 test rig application")
end function

' /**
'  * @member begin
'  * @memberof module:MainScene
'  * @instance
'  * @description This would be called when all initial data is loaded. The app would show a loading spinner and loading background until this point
'  * @param {paramType} paramDescription
'  * @returns {returnType} returnDescription
'  */
function begin(args = invalid)
  m.log.info("begin")
  m.top._global = m.global
  mioc.createContainer()
  fontManager = createObject("roSGNode", "mv_FontManager")
  mioc.setInstance("fontManager", fontManager)
  mc.setOrAddNodeField(m.global, "fontManager", fontManager)

  appController = m.top.findNode("mainGroup").createChild("AppController")
  appController@._initialize()
  mv.setFocus(appController)
end function
