function init()
  m.rect = m.top.findNode("rect")
  m.label = m.top.findNode("label")
  m.top.observeField("itemContent", "itemContentChanged")
  m.top.observeField("focusPercent", "focusPercentChanged")

end function

function itemContentChanged()
  m.label.text = "S2 " + m.top.itemContent.title
end function

function focusPercentChanged()
  ' print "focusPercent for item "; m.top.index; " changed to "; m.top.focusPercent
end function
