import "pkg:/source/roku_modules/maestro/core/Utils.brs"
import "pkg:/source/ListMixin.bs"
import "pkg:/source/ItemDelegateMixin.bs"
import "pkg:/source/RowItemScroller.bs"
import "pkg:/source/RowItemViewManager.bs"
import "pkg:/source/ItemFocusManager.bs"
import "pkg:/source/roku_modules/maestro/view/BaseView.brs"
import "pkg:/source/cells/BaseCell.bs"

@node("SubHeroCell", "mv_BaseView")
class SubHeroCell extends ml.BaseCell

  private poster
  private rectangle
  private label
  private bgRect

  private lastContent
  private isViewCreated = false
  private posterSize = [450, 320.0]

  function new()
    super()
    m.createViews()
  end function

  private function createViews() as void
    if m.isViewCreated
      return
    end if
    m.isViewCreated = true
    m.bgRect = mc.createSGNode("mv_Rectangle", m.top, "bgRect", {
      size: [m.posterSize[0] * 2, m.posterSize[1]]
      color: "#2222aa"
    })
    m.poster = mc.createSGNode("mv_Poster", m.top, "poster", {
      translation: [0, 0]
      loadDisplayMode: "scaleToFill"
      loadingBitmapUri: "http://via.placeholder.com/450x320"
      failedBitmapUri: "http://via.placeholder.com/450x320"
      loadWidth: m.posterSize[0]
      loadHeight: m.posterSize[1]
      size: m.posterSize
      uri: "http://via.placeholder.com/450x320"
    })
    m.rectangle = mc.createSGNode("mv_Rectangle", m.top, "rectangle", {
      opacity: 0.4
      color: "#000000"
      width: m.posterSize[0] * 2
      height: 20
    })
    m.label = mc.createSGNode("mv_Label", m.top, "label", {
      width: m.posterSize[0]
      fontKey: "mediumBold,30"
      horizAlign: "left"
      translation: [m.posterSize[0] + 20, 10]
    })
    m.label = m.top.findNode("label")
  end function

  protected override function onContentChange()
    ? ">>>>>>>>>>>>>>>>>>> SC 1 "; m.list.isScrolling ; m.row.isScrolling
    if m.content = invalid or not m.content.isSamenode(m.lastContent)
      ' ? " SC 2"
      m.lastContent = m.content
      m.createViews()
      m.label.text = "C:" + m.lastContent.title
      m.poster.uri = m.lastContent.HDGRIDPOSTERURL
      'TODO part of initial state
      m.onScrollingChange(m.list.isScrolling, false)
    end if
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ delegate
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  private function onScrollingChange(isScrolling as boolean, isLong as boolean)
    m.label.visible = not (isScrolling and isLong)
  end function

  private function onWillEnter(direction)
    ' ? "SC: onCellWillEnter " ; " " ; direction
    m.onContentChange()
  end function

  private function onWillExit(direction)
    ' ? "SC: onCellWillExit " ; " " ; direction
  end function

  private function onDidEnter(direction)
    ' ? "SC: onCellDidEnter " ; " " ; direction
    ' m.onContentChange()
  end function

  private function onDidExit(direction)
    ' ? "SC: onCellDidExit " ; " " ; direction
  end function

  private function onWillGainFocus(direction)
    ' ? "SC: onCellWillGainFocus " ; " " ; direction
  end function

  private function onWillLoseFocus(direction)
    ' ? "SC: onCellWillLoseFocus " ; " " ; direction
  end function

  private function onDidGainFocus(direction)
    ' ? "SC: onCellDidGainFocus " ; " " ; direction
  end function

  private function onDidLoseFocus(direction)
    ' ? "SC: onCellDidLoseFocus " ; " " ; direction
    if direction = 1
    end if
  end function

  private function onGainingFocus(direction, fraction)
    ' ? "SC: onGainingFocus " ; " " ; direction ; " "  ; fraction
  end function

  private function onLosingFocus(direction, fraction)
    ' ? "SC: onLosingFocus " ; " " ; direction ; " " ; fraction
    if direction = 1
    end if
  end function

end class